import 'dart:math';
import 'package:cloud_firestore/cloud_firestore.dart';

/// Model for a librarian access token generated by an admin.
class AccessToken {
  final String token;
  final String createdByUid;
  final DateTime createdAt;
  final DateTime expiresAt;
  final bool used;
  final String? usedByUid;

  const AccessToken({
    required this.token,
    required this.createdByUid,
    required this.createdAt,
    required this.expiresAt,
    this.used = false,
    this.usedByUid,
  });

  bool get isExpired => DateTime.now().isAfter(expiresAt);
  bool get isValid => !used && !isExpired;

  factory AccessToken.fromJson(Map<String, dynamic> json, String token) {
    return AccessToken(
      token: token,
      createdByUid: json['createdByUid'] as String? ?? '',
      createdAt: (json['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      expiresAt: (json['expiresAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      used: json['used'] as bool? ?? false,
      usedByUid: json['usedByUid'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'createdByUid': createdByUid,
      'createdAt': Timestamp.fromDate(createdAt),
      'expiresAt': Timestamp.fromDate(expiresAt),
      'used': used,
      if (usedByUid != null) 'usedByUid': usedByUid,
    };
  }

  /// Generate a random 6-character alphanumeric token.
  static String generateCode() {
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // no 0/O/1/I confusion
    final rng = Random.secure();
    return List.generate(6, (_) => chars[rng.nextInt(chars.length)]).join();
  }
}
