// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw8R6t27-QezIdgcsMBzl4qitx5IIU54Q',
    appId: '1:1043576322716:web:3604604e48179cfd938b59',
    messagingSenderId: '1043576322716',
    projectId: 'lib-management-d6460',
    authDomain: 'lib-management-d6460.firebaseapp.com',
    storageBucket: 'lib-management-d6460.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjuZD6YIPq5o2GHOBbURfEgGQxDfHVcvg',
    appId: '1:1043576322716:android:d7e9930b71557916938b59',
    messagingSenderId: '1043576322716',
    projectId: 'lib-management-d6460',
    storageBucket: 'lib-management-d6460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC706x7Wr6kT123e1zTuaZUOA8ytJlfzzo',
    appId: '1:1043576322716:ios:1a3179876d8c0593938b59',
    messagingSenderId: '1043576322716',
    projectId: 'lib-management-d6460',
    storageBucket: 'lib-management-d6460.firebasestorage.app',
    androidClientId: '1043576322716-or5ervgc2fmpfihsrc5pchbohip6h546.apps.googleusercontent.com',
    iosClientId: '1043576322716-dtidespsfu15qiah562ru894osd1mo7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC706x7Wr6kT123e1zTuaZUOA8ytJlfzzo',
    appId: '1:1043576322716:ios:1a3179876d8c0593938b59',
    messagingSenderId: '1043576322716',
    projectId: 'lib-management-d6460',
    storageBucket: 'lib-management-d6460.firebasestorage.app',
    androidClientId: '1043576322716-or5ervgc2fmpfihsrc5pchbohip6h546.apps.googleusercontent.com',
    iosClientId: '1043576322716-dtidespsfu15qiah562ru894osd1mo7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw8R6t27-QezIdgcsMBzl4qitx5IIU54Q',
    appId: '1:1043576322716:web:00731085d623254b938b59',
    messagingSenderId: '1043576322716',
    projectId: 'lib-management-d6460',
    authDomain: 'lib-management-d6460.firebaseapp.com',
    storageBucket: 'lib-management-d6460.firebasestorage.app',
  );

}